/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-builder/index.ts to modify the generation of this file.


import { ComponentBuilder } from '@sitecore-jss/sitecore-jss-nextjs';


import * as AboutSection from 'src/components/AboutSection';
import * as ClientsSection from 'src/components/ClientsSection';
import * as ContactSection from 'src/components/ContactSection';
import * as Footer from 'src/components/Footer';
import * as Header from 'src/components/Header';
import * as HeroSection from 'src/components/HeroSection';
import * as ServicesSection from 'src/components/ServicesSection';
import * as SitecoreFields from 'src/components/SitecoreFields';
import * as TestimonialsSection from 'src/components/TestimonialsSection';

export const components = new Map();

components.set('AboutSection', AboutSection);
components.set('ClientsSection', ClientsSection);
components.set('ContactSection', ContactSection);
components.set('Footer', Footer);
components.set('Header', Header);
components.set('HeroSection', HeroSection);
components.set('ServicesSection', ServicesSection);
components.set('SitecoreFields', SitecoreFields);
components.set('TestimonialsSection', TestimonialsSection);

export const componentBuilder = new ComponentBuilder({ components });

export const moduleFactory = componentBuilder.getModuleFactory();
