/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.
const config = {};
config.sitecoreApiKey = process.env.SITECORE_API_KEY || '08BECE0B-5FC2-4A9E-A31B-E8AC709A46BF';
config.sitecoreApiHost = process.env.SITECORE_API_HOST || 'https://kfiasc.dev.local';
config.sitecoreSiteName = process.env.SITECORE_SITE_NAME || 'DACO';
config.graphQLEndpointPath = process.env.GRAPH_QL_ENDPOINT_PATH || '/sitecore/api/graph/edge';
config.defaultLanguage = process.env.DEFAULT_LANGUAGE || 'en';
config.graphQLEndpoint = process.env.GRAPH_QL_ENDPOINT || 'https://kfiasc.dev.local/sitecore/api/graph/edge';
config.layoutServiceConfigurationName = process.env.LAYOUT_SERVICE_CONFIGURATION_NAME || 'sxa-jss';
config.publicUrl = process.env.PUBLIC_URL || 'http://localhost:8080';
module.exports = config;
